### ISSUE TITLE
min-font-size(auto) falls back to media query min-width before ratio

### ISSUE THREAD

**Issue by kohlmannj** [nytpi/nytpi-sass-utils#11]
For example:

```scss
.selector {
    @include size-class(regular) {
        @include font-size(28, vw);
    }
}
```

…results in this CSS:

```css
@media (min-width: 540px) {
    .selector {
        font-size: 5.90625px;
    }
}
```

…**instead of** this CSS:

```css
@media (min-width: 1200px) {
    .selector {
        font-size: 13.125px;
    }
}
```

This is a logical error [somewhere in limit-font-size()](https://github.com/nytpi/nytpi-sass-utils/blob/development/sass/font-size/_limit-font-size.scss#L71) when it determines how to handle the `auto` argument.
