### ISSUE TITLE
New unit conversion system

### ISSUE THREAD

**Issue by kohlmannj** [nytpi/nytpi-sass-utils#19]
```sass
.dingus
    @media (max-width: 1605px)
        +pspx-context(32@2x as vw)
            +pspx(width, 640)
            +pspx(height, 480)
            +pspx(font-size, 64)
            +pspx(line-height, 72)
            +pspx(margin, 0 auto 32)
            +pspx(padding-bottom, 48)
```

Mixins would be the only way to implement this consistently, since outputting to units like `vw` may need to render multiple output properties (and/or media queries).

**Comment by kohlmannj** [comment]
Another take: a mixin that operates like an extension of a media query:

```scss
.dingus {
    @include pspx-context(max-width: 1605px, pspx-base: 32, pspx-scale: 2, pspx-output: vw) {
        width: 640pspx;
        height: 480pspx;
        font-size: 64pspx;
        line-height: 72pspx;
        margin: 0 auto 32pspx;
        padding-bottom: 48pspx;
    }
}
```

Not aware of any way to access and/or transform properties and values declared within a content block. That's currently unsupported, right @chriseppstein?

**Comment by kohlmannj** [comment]
This would be the cleanest coding style I can think of, but would be limited to Sass functions:

```scss
.dingus {
    @include pspx-context($max-width: 1605px, $pspx-base: 32, $pspx-scale: 2, $pspx-output: vw) {
        width: pspx(640);
        height: pspx(480);
        font-size: pspx(64);
        line-height: pspx(72);
        margin: 0 auto pspx(32);
        padding-bottom: pspx(48);
    }
}
```

Code using the current `em()` function in tandem with the `font-size()` mixin looks a lot like the above. A hypothetical `pspx-context()` mixin could indeed set a `font-size()` value and have all other values output in `em` to get around the mixin issue…

My concern there: if `pspx-context()` sets a `font-size` value, you wouldn't be able to set `font-size` _within_ the `pspx-context()` content block, unless you choose to set a `font-size` value on a descendant selector. (Again, this mirrors current usage and limitations of `font-size()` mixin + `em()` function.)
