### ISSUE TITLE
max-font-size() mixin (to add control and flexibility to the automatic upscaling cap currently implemented)

### ISSUE THREAD

**Issue by kohlmannj** [nytpi/nytpi-sass-utils#3]
Currently, the `font-size()` mixin, when used to output font sizes in `vw` units, sets up a media query to prevent the font-size from continuing to increase past the NYT5's "shell" maximum width of 1605 pixels.

This is an excellent layout optimization, but it's also "magic" / hidden behavior that could be *very* confusing.

Arguably the `font-size()` mixin should *not* automatically default to upscaling font-size value past 1605 pixels, and instead the developer should be given opt-in control over this behavior through a `max-font-size()` mixin.

**Comment by kohlmannj** [comment]
The alternative would be some kind of configurable opt-in that prevents text from growing past the max width of the active breakpoint:

```scss
.selector {
    @include size-class(desktop) {
        @include font-size(64, vw) {
            @include max-font-size;
            @include min-font-size(48);
        }
    }
}
```

Example output:

```css
@media (min-width: 1280px) {
    .selector {
        font-size: 2.5vw;
    }
}

// min-font-size() mixin output, which reverse-solves for a max-width value
@media (max-width: 960px) {
    .selector {
        font-size: 24px;
    }
}

// max-font-size() mixin output, which sets up a media query for when we exceed this size class's widest breakpoint's max-width (this is a little tricky to generalize with `desktop` because of the `shell` breakpoint)
@media (min-width: 1605px) {
    .selector {
        font-size: 40.125px;
    }
}
```
